#!/bin/bash
# find all language files and run 'findSymbols.py' on them
FILES=./*.h
for f in $FILES
do
  python3 ./findSymbols.py $f
done

cd fonts

# find all *.sh files (generated by 'findSymbols.py') and run them
FILES=./*.sh
for f in $FILES
do
  bash $f
  rm $f
done

# generate ASCII font
./bdf2u8g -l 0 -s 0 -b 32 -e 127 -f 1 master.bdf ASCII font_ASCII.h

# from the generated *.bdf fonts create *.h files
FILES=./master_*.bdf
for f in $FILES
do
  INPUT=$f
  SUBSTRING1=$(echo $INPUT| cut -d'_' -f 2-)
  SUBSTRING=$(echo .$SUBSTRING1| cut -d'.' -f 2)
  NCHARS=$(grep -o 'STARTCHAR' $f | wc -l)
  NCHARSM=$(echo $(($NCHARS-1)))
  #echo "./bdf2u8g -l 0 -s 0 -b 0 -e $NCHARSM -f 0  $f $SUBSTRING font_$SUBSTRING.h"
  ./bdf2u8g -l 0 -s 0 -b 0 -e $NCHARSM -f 0 $f $SUBSTRING font_$SUBSTRING.h
  rm $f
done

rm symbols_*.txt
